-- MySQL Script generated by MySQL Workbench
-- Wed May  9 11:28:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yoAlquilo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yoAlquilo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yoAlquilo` DEFAULT CHARACTER SET utf8 ;
USE `yoAlquilo` ;

-- -----------------------------------------------------
-- Table `yoAlquilo`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoAlquilo`.`Persona` (
  `idPersona` INT NOT NULL,
  `codigoPersona` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraceña` VARCHAR(45) NULL,
  `tipoPersona` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yoAlquilo`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoAlquilo`.`Comentario` (
  `idComentario` INT NOT NULL,
  `Comentario_Text` VARCHAR(45) NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Persona_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Comentario_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `yoAlquilo`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yoAlquilo`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoAlquilo`.`Lugar` (
  `idLugar` INT NOT NULL AUTO_INCREMENT,
  `ubicacion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `foto` VARCHAR(50) NULL,
  `precio` VARCHAR(45) NULL,
  `restricciones` VARCHAR(45) NULL,
  `fecha_publica` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idLugar`),
  INDEX `fk_Lugar_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Lugar_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `yoAlquilo`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
